twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        gcomics: '@App\Globals\Comics'
        gwriters: '@App\Globals\Writers'
        gdesigners: '@App\Globals\Designers'
        geditors: '@App\Globals\Editors'
        glicences: '@App\Globals\Licences'

when@test:
    twig:
        strict_variables: true
